import * as THREE from 'three';

// Simple, dependency-free value-noise (no external noise library needed).
function hash(x, z) {
    const s = Math.sin(x * 127.1 + z * 311.7) * 43758.5453123;
    return s - Math.floor(s);
}
function smoothNoise(x, z) {
    const ix = Math.floor(x), iz = Math.floor(z);
    const fx = x - ix, fz = z - iz;
    const a = hash(ix, iz), b = hash(ix + 1, iz);
    const c = hash(ix, iz + 1), d = hash(ix + 1, iz + 1);
    const ux = fx * fx * (3 - 2 * fx);
    const uz = fz * fz * (3 - 2 * fz);
    return a * (1 - ux) * (1 - uz) + b * ux * (1 - uz) + c * (1 - ux) * uz + d * ux * uz;
}
function fbm(x, z, octaves = 4) {
    let total = 0, amp = 1, freq = 1, maxAmp = 0;
    for (let i = 0; i < octaves; i++) {
        total += smoothNoise(x * freq, z * freq) * amp;
        maxAmp += amp;
        amp *= 0.5;
        freq *= 2;
    }
    return total / maxAmp;
}

/**
 * Large-scale procedural terrain. Height is generated by a cheap analytic
 * function (fbm noise) so the same function can be sampled by physics for
 * ground collision without needing to raycast the actual mesh.
 *
 * A flattened, smooth disc is carved out around the airport (0,0) so runways
 * stay level, blending smoothly into the surrounding hills.
 */
export class Terrain {
    constructor(scene, options = {}) {
        this.scene = scene;
        this.size = options.size || 16000; // metres, total width/depth
        this.segments = options.segments || 220;
        this.maxHeight = options.maxHeight || 320;
        this.airportRadius = options.airportRadius || 1400;
        this.airportBlend = options.airportBlend || 900;

        this.group = new THREE.Group();
        this.group.name = 'Terrain';
        scene.add(this.group);

        this._buildGround();
        this._scatterTrees();
    }

    // Public height function used by physics + object placement.
    getHeight(x, z) {
        const distFromCenter = Math.hypot(x, z);
        if (distFromCenter < this.airportRadius) return 0;

        const raw = fbm(x * 0.0009, z * 0.0009, 5) * 2 - 1; // -1..1
        const hills = Math.pow(Math.abs(raw), 1.4) * Math.sign(raw) * this.maxHeight;
        const ridges = fbm(x * 0.003, z * 0.003, 3) * 18;
        let height = hills + ridges;

        if (distFromCenter < this.airportRadius + this.airportBlend) {
            const t = (distFromCenter - this.airportRadius) / this.airportBlend;
            const smoothT = t * t * (3 - 2 * t);
            height *= smoothT;
        }
        return height;
    }

    _buildGround() {
        const geo = new THREE.PlaneGeometry(this.size, this.size, this.segments, this.segments);
        geo.rotateX(-Math.PI / 2);
        const pos = geo.attributes.position;
        const colors = new Float32Array(pos.count * 3);
        const grassLow = new THREE.Color(0x4a7c3c);
        const grassHigh = new THREE.Color(0x8a8266);
        const rock = new THREE.Color(0x8a8478);
        const snow = new THREE.Color(0xf2f4f6);

        for (let i = 0; i < pos.count; i++) {
            const x = pos.getX(i);
            const z = pos.getZ(i);
            const h = this.getHeight(x, z);
            pos.setY(i, h);

            let color;
            const t = THREE.MathUtils.clamp(h / this.maxHeight, 0, 1);
            if (t < 0.25) color = grassLow.clone().lerp(grassHigh, t / 0.25);
            else if (t < 0.65) color = grassHigh.clone().lerp(rock, (t - 0.25) / 0.4);
            else color = rock.clone().lerp(snow, (t - 0.65) / 0.35);

            colors[i * 3] = color.r;
            colors[i * 3 + 1] = color.g;
            colors[i * 3 + 2] = color.b;
        }
        geo.setAttribute('color', new THREE.BufferAttribute(colors, 3));
        geo.computeVertexNormals();

        const mat = new THREE.MeshStandardMaterial({
            vertexColors: true,
            roughness: 1,
            metalness: 0
        });
        const mesh = new THREE.Mesh(geo, mat);
        mesh.receiveShadow = true;
        mesh.name = 'GroundMesh';
        this.group.add(mesh);

        // A large flat water plane far below hill level for coastal-looking edges.
        const waterGeo = new THREE.PlaneGeometry(this.size * 1.2, this.size * 1.2);
        waterGeo.rotateX(-Math.PI / 2);
        const waterMat = new THREE.MeshStandardMaterial({
            color: 0x1c5c78, roughness: 0.15, metalness: 0.3, transparent: true, opacity: 0.85
        });
        const water = new THREE.Mesh(waterGeo, waterMat);
        water.position.y = -6;
        water.name = 'Water';
        this.group.add(water);
    }

    _scatterTrees() {
        // Instanced trees so thousands can render cheaply.
        const trunkGeo = new THREE.CylinderGeometry(0.5, 0.7, 4, 6);
        const leavesGeo = new THREE.ConeGeometry(3.2, 7, 7);
        const trunkMat = new THREE.MeshStandardMaterial({ color: 0x6b4a2f, roughness: 1 });
        const leavesMat = new THREE.MeshStandardMaterial({ color: 0x2f6b3a, roughness: 0.9 });

        const count = 3500;
        const trunkMesh = new THREE.InstancedMesh(trunkGeo, trunkMat, count);
        const leavesMesh = new THREE.InstancedMesh(leavesGeo, leavesMat, count);
        trunkMesh.castShadow = true;
        leavesMesh.castShadow = true;

        const dummy = new THREE.Object3D();
        let placed = 0;
        let attempts = 0;
        while (placed < count && attempts < count * 4) {
            attempts++;
            const angle = Math.random() * Math.PI * 2;
            const radius = this.airportRadius + this.airportBlend * 0.6 + Math.random() * (this.size * 0.42);
            const x = Math.cos(angle) * radius;
            const z = Math.sin(angle) * radius;
            const h = this.getHeight(x, z);
            if (h < -2) continue; // skip water
            const scale = 0.7 + Math.random() * 0.9;

            dummy.position.set(x, h + 2 * scale, z);
            dummy.rotation.y = Math.random() * Math.PI * 2;
            dummy.scale.setScalar(scale);
            dummy.updateMatrix();
            trunkMesh.setMatrixAt(placed, dummy.matrix);

            dummy.position.y = h + 6.5 * scale;
            dummy.updateMatrix();
            leavesMesh.setMatrixAt(placed, dummy.matrix);
            placed++;
        }
        trunkMesh.count = placed;
        leavesMesh.count = placed;
        trunkMesh.instanceMatrix.needsUpdate = true;
        leavesMesh.instanceMatrix.needsUpdate = true;
        trunkMesh.name = 'TreeTrunks';
        leavesMesh.name = 'TreeLeaves';
        this.group.add(trunkMesh, leavesMesh);
    }
}
